### ISSUE TITLE
sorry, this code just have the test part ?? 

### ISSUE THREAD

**Issue by meshiguge** [geduo15/Very-Deep-Convolutional-Networks-for-Natural-Language-Processing-in-tensorflow#1]

**Comment by geduo15** [comment]
Well, I'm so lazy. The old version had some mistakes , I deleted  it, I will push the new version as soon as possible.
Thank you!

**Comment by geduo15** [comment]
@meshiguge  , Well, I'm so lazy. The old version had some mistakes , I deleted it, I will push the new version as soon as possible.
Thank you!

**Comment by geduo15** [comment]
@meshiguge  I have updated.
