### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by AK-mocha** [geduo15/Very-Deep-Convolutional-Networks-for-Natural-Language-Processing-in-tensorflow#3]
Hi there,

Thank you for showing your code.
Can you please tell us where we can get the dataset from?

Cheers

**Comment by geduo15** [comment]
Hi,
The data is from
https://drive.google.com/drive/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M
,
I get the information from http://xzh.me/
Best wishes

2017-07-25 22:02 GMT+08:00 akirakitamura19 <notifications@github.com>:

**Comment by AK-mocha** [comment]
Hi

Thank you so much. It is really helpful.

Cheers
